print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/JeremySlavitz/Desktop/L-U-G-E_final/LUGE2/Assets/luge2.mb"`)
{		
	file -o "/Users/JeremySlavitz/Desktop/L-U-G-E_final/LUGE2/Assets/luge2.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/JeremySlavitz/Desktop/L-U-G-E_final/LUGE2/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/JeremySlavitz/Desktop/L-U-G-E_final/LUGE2/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/JeremySlavitz/Desktop/L-U-G-E_final/LUGE2/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
